name: 只打包-24.10

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  pack:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - name: 检查 Actions
      uses: actions/checkout@v4

    - name: 打包 N1 固件
      uses: unifreq/openwrt_packit@master
      env:
        WHOAMI: ham
        OPENWRT_ARMVIRT: https://github.com/ham-0915/N1-0407/releases/download/lede-24.10_20260718/openwrt-armsr-armv8-generic-rootfs.tar.gz
        PACKAGE_SOC: s905d
        KERNEL_AUTO_LATEST: true
        KERNEL_REPO_URL: ophub/kernel
        KERNEL_USAGE: flippy
        KERNEL_VERSION_NAME: 6.6.y_6.12.y

    - name: 上传到 Release
      uses: ncipollo/release-action@v1
      with:
        name: "N1-测试打包-24.10-${{ env.PACKAGED_OUTPUTDATE }}"
        tag: "test-24.10-${{ env.PACKAGED_OUTPUTDATE }}"
        artifacts: "${{ env.PACKAGED_OUTPUTPATH }}/*"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ### 测试打包
          - **rootfs 来源**：ham-0915/N1-0407/24.10
          - **内核来源**：ophub/kernel（unifreq flippy 内核）
          - **内核版本**：6.y.y 最新
          - **网关地址**：192.168.123.2
          - **登录账户**：root
          - **登录密码**：password
          
